.PHONY: build run test lint clean tidy fmt vet{{if has "grpc"}} proto{{end}}{{if or (has "postgres") (has "redis")}} docker-up docker-down{{end}}

BINARY := server
CONFIG ?= configs/config.local.yaml

build:
	go build -o bin/$(BINARY) ./cmd/server

run: build
	./bin/$(BINARY) -config $(CONFIG)

test:
	go test -v -race -count=1 ./...

lint:
	golangci-lint run ./...
{{if has "grpc"}}
proto:
	cd proto && buf generate
{{end}}
{{- if or (has "postgres") (has "redis")}}
docker-up:
	docker compose -f deploy/docker-compose.yml up -d --build

docker-down:
	docker compose -f deploy/docker-compose.yml down
{{end}}
tidy:
	go mod tidy

fmt:
	gofumpt -l -w .

vet:
	go vet ./...

clean:
	rm -rf bin/
